Add 'Usless Compound' Recipe and 'UselessCompoundVisitor'
openrewrite/rewrite pull request #1709
Opened 2022-04-25 23:10 UTC by JLLeitschuh

Cleans up statements like:
 - `b &= true` -> removed
 - `b &= false` -> `b = false`
 - `b |= true` -> removed
 - `b |= false` -> `b = false`

2022-04-25 23:11 UTC, JLLeitschuh commented
Use case: https://github.com/openrewrite/rewrite-java-security/pull/19/files#r858093366

2022-04-26 01:53 UTC, traceyyoshima requested changes

2022-04-26 01:53 UTC, traceyyoshima commented on rewrite-java/src/main/java/org/openrewrite/java/cleanup/UselessCompound.java
> +public class UselessCompound extends Recipe {
The recipe name may be interpreted as a useless compound, I think this would read better as something like, `SimplyCompoundStatements`.

2022-04-26 01:53 UTC, traceyyoshima commented on rewrite-java/src/main/java/org/openrewrite/java/cleanup/UselessCompound.java
> +        return "Useless compound statement";
Similar suggestions here and in the description.

2022-04-26 01:53 UTC, traceyyoshima commented on rewrite-java/src/main/java/org/openrewrite/java/cleanup/UselessCompoundVisitor.java
> +public class UselessCompoundVisitor<P> extends JavaVisitor<P> {
Similar rename.

2022-04-26 01:53 UTC, traceyyoshima commented on rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
> +    inner class UslessCompoundTck : UselessCompoundTest
Quick typo.

2022-04-26 01:53 UTC, traceyyoshima commented on rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/UselessCompoundTest.kt
> +    fun removeUselessCompoundAnd(jp: JavaParser) = assertChanged(
Similar to previous suggestions, I'd rename this to something like simplifyCompoundAnd.

2022-04-26 19:43 UTC, traceyyoshima requested changes

2022-04-26 19:59 UTC, traceyyoshima approved these changes
LGTM, thank you for the PR @JLLeitschuh!

2022-04-26 20:02 UTC, merged