Add ChangeJavaCompatibility recipe
openrewrite/rewrite pull request #1960
Opened 2022-06-27 17:32 UTC by shanman190

2022-06-27 18:04 UTC, sambsnyd requested changes
Good stuff. Thorough tests. 👍

2022-06-27 18:04 UTC, sambsnyd commented on rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeJavaCompatibility.java
> +            description = "The Java version to update source compatibility to",
Consider mentioning the valid values. If someone wants Java 8 should they put in "8" or "1.8"?

2022-06-28 23:20 UTC, shanman190 commented
Not sure about the failures. This was rebased onto the tip of `main`, but there's still some errors. 🤔

2022-06-29 00:47 UTC, shanman190 commented
Latest rebase is now working. :)

2022-06-29 01:47 UTC, merged