Added support for line continuations.
openrewrite/rewrite pull request #2502
Opened 2022-12-08 20:45 UTC by traceyyoshima

fixes #2473

2022-12-08 22:53 UTC, tkvangorder requested changes
See my changes. We need to attach the continuations to each entry (and reset the continuations each time) 

Without these changes, you can see the side effects by adding a second property to your test: 

```
                \
                
                k\
                 e\
                
                  y \
                   = \
                
                    v\
                
                     al\
                      ue
  
                fred=fred
```

2022-12-08 22:53 UTC, tkvangorder commented on rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java
> +                    continuation.delete(0, continuation.length());
```suggestion
                    continuation.setLength(0);
```

2022-12-08 22:53 UTC, tkvangorder commented on rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java
>                      if (content != null) {
```suggestion
                    if (content != null) {
                        if (!continuationPositions.isEmpty() && content instanceof Properties.Entry) {
                            content = content.withMarkers(content.getMarkers().addIfAbsent(new EntryContinuation(randomId(), continuationPositions)));
                            continuationPositions = new HashMap<>();
                        }
```

2022-12-08 22:53 UTC, tkvangorder commented on rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java
> +            continuation.delete(0, continuation.length());
```suggestion
            continuation.setLength(0);
```

2022-12-08 22:58 UTC, tkvangorder commented
Also, if we mutate an entry that has continuation markers, we either need to clear the markers or compute updates to the positioning. Failing to do that, we are going to run into issues with printing.

2022-12-10 01:37 UTC, traceyyoshima commented
> Also, if we mutate an entry that has continuation markers, we either need to clear the markers or compute updates to the positioning. Failing to do that, we are going to run into issues with printing.

The issue is fixed via updates to with(s) and a few changes to the ProperiesParser.

2023-01-10 02:42 UTC, sambsnyd commented
I'm going to close this PR for now since it isn't ready to commit and no one is actively working on this

2023-01-10 02:42 UTC, closed without merging