Gradle Recipe AddDependency without version
openrewrite/rewrite pull request #3210
Opened 2023-05-07 21:02 UTC by nicolasb29

For [#3208](https://github.com/openrewrite/rewrite/issues/3208)

2023-05-08 01:48 UTC, shanman190 requested changes
@nicolasb29, thanks for your contribution! I've added a couple of minor comments.

2023-05-08 08:50 UTC, nicolasb29 commented on rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java
>      String version;
@shanman190 I just added the annotation ```@Nullable``` on the version field.

2023-05-08 08:51 UTC, nicolasb29 commented on rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java
> +                        configuration + " group: \"" + groupId + "\", name: \"" + artifactId + "\"" + (version == null ? "" :  ", version: \"" + version + "\"") + (version == null || classifier == nu
@shanman190 I modified the map notation to keep classifier even if version is not present. I also added some tests.

2023-05-09 20:48 UTC, shanman190 approved these changes
LGTM! Thank you for the contribution, @nicolasb29!

2023-05-09 20:48 UTC, merged