Created public addAnnotation methods
openrewrite/rewrite pull request #43
Opened 2020-09-28 21:00 UTC by SofiaBrittoSchwartz

Created public versions of the addAnnotation methods and created a public static buildAnnotation method in J.Annotation for ease of access.

2020-09-28 21:15 UTC, jkschneider commented
@SofiaBrittoSchwartz For better discovery, could we place these as non-static methods on `J.MethodDecl` and `J.ClassDecl` respectively?

2020-09-28 21:57 UTC, jkschneider requested changes

2020-09-28 21:57 UTC, jkschneider commented on rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
> +                J.ClassDecl c,
You can remove this parameter `c`, as it should be able to refer to `this`. Suggestion is to make this non-static.

2020-09-28 21:57 UTC, jkschneider commented on rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
> +                boolean isTopLevelClass,
You should be able to simplify and remove this now. Add the annotation and then apply `AutoFormat`. It's only used to detect a special case of formatting that should be caught in `AutoFormat`.

2020-09-28 21:57 UTC, jkschneider commented on rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
> +                JavaFormatter formatter
`AutoFormat` does not need to have a `JavaFormatter` passed to it.

2020-11-04 18:23 UTC, jkschneider approved these changes

2020-11-13 20:01 UTC, sambsnyd requested changes
Good work!

2020-11-13 20:01 UTC, sambsnyd commented on rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
> +        ) {
Same question here as I had about `J.ClassDecl.addAnnotation()`

2020-11-13 21:35 UTC, SofiaBrittoSchwartz commented on rewrite-java/src/main/java/org/openrewrite/java/AddAnnotation.java
> +                                    m.getName().getFormatting();
Refactored to an if/else statement

2020-11-13 21:39 UTC, sambsnyd approved these changes

2020-11-13 21:42 UTC, merged